/**
 * Generates the API reference pages and adapts TypeDoc's markdown output for
 * Fumadocs.
 *
 * TypeDoc emits plain markdown with no frontmatter, scope-prefixed directories
 * (`@webgpu-text/layout`), and `.mdx`-suffixed relative links. Fumadocs needs
 * frontmatter for titles and search, dislikes `@` in route segments, and
 * resolves links without the file extension. This script runs TypeDoc into a
 * staging directory, rewrites the tree there, and swaps it into place once it
 * is complete.
 *
 * Output is gitignored and regenerated by `predev`/`prebuild`, so it never goes
 * stale and never appears in a review diff.
 */
import { execFileSync } from 'node:child_process'
import { readdirSync, readFileSync, renameSync, rmSync, writeFileSync } from 'node:fs'
import { resolve } from 'node:path'

const appRoot = resolve(import.meta.dirname, '..')
const apiRoot = resolve(appRoot, 'content/docs/api')
const scope = '@webgpu-text'

/** Package slugs in the order they should appear in the sidebar. */
const packages = ['font', 'layout', 'sdf', 'three'] as const

/** Human-facing titles and blurbs for each generated package section. */
const packageMeta: Record<(typeof packages)[number], { title: string; description: string }> = {
  font: {
    title: 'font',
    description:
      'Font loading, HarfBuzz shaping, font facts, coverage, and numeric glyph outlines.',
  },
  layout: {
    title: 'layout',
    description: 'Text preparation and renderer-neutral layout of raw text or resolved runs.',
  },
  sdf: {
    title: 'sdf',
    description: 'Deterministic CPU signed-distance-field generation from numeric outlines.',
  },
  three: {
    title: 'three',
    description: 'Instanced Three.js WebGPU rendering of a completed layout.',
  },
}

/** Section directories TypeDoc emits inside each package, in sidebar order. */
const sections = ['functions', 'classes', 'interfaces', 'type-aliases', 'variables', 'enumerations']

function walk(directory: string): string[] {
  return readdirSync(directory, { withFileTypes: true }).flatMap((entry) => {
    const path = resolve(directory, entry.name)
    return entry.isDirectory() ? walk(path) : entry.name.endsWith('.mdx') ? [path] : []
  })
}

/** Derives a page title from TypeDoc's leading `# Kind: name()` heading. */
function pageTitle(source: string, fallback: string): string {
  const heading = /^#\s+(.+)$/m.exec(source)?.[1]?.trim()
  if (!heading) return fallback
  return heading.replace(/^(?:Function|Class|Interface|Type Alias|Variable|Enumeration):\s*/, '')
}

function writeMeta(directory: string, title: string, pages: string[]): void {
  writeFileSync(resolve(directory, 'meta.json'), `${JSON.stringify({ title, pages }, null, 2)}\n`)
}

// Build into a staging directory and swap it in only once complete. Fumadocs
// indexes content/docs eagerly, so a tree that is briefly absent or partially
// written makes the Next build fail on stale module references.
const stageRoot = resolve(appRoot, 'content/docs/.api-stage')
rmSync(stageRoot, { force: true, recursive: true })
execFileSync('npx', ['typedoc', '--out', stageRoot], { cwd: appRoot, stdio: 'inherit' })

// TypeDoc nests packages under the npm scope; Fumadocs routes read better
// without an "@webgpu-text" segment, so lift each package up one level.
const scopeRoot = resolve(stageRoot, scope)
for (const name of packages) {
  renameSync(resolve(scopeRoot, name), resolve(stageRoot, name))
}
rmSync(scopeRoot, { force: true, recursive: true })
rmSync(resolve(stageRoot, '_media'), { force: true, recursive: true })

for (const file of walk(stageRoot)) {
  const original = readFileSync(file, 'utf8')
  const title = pageTitle(original, 'API')
  const body = original
    // Links lose the extension, and the scope segment no longer exists.
    .replace(/\]\(([^)]+)\.mdx(#[^)]*)?\)/g, ']($1$2)')
    .replace(new RegExp(`\\]\\((\\.{1,2}/)*${scope}/`, 'g'), '](../')
    // The leading heading is redundant once frontmatter supplies the title.
    .replace(/^#\s+.+\n+/, '')
    // Absolute source paths leak the generating machine's layout.
    .replace(/^Defined in: .*$/gm, (line) =>
      line.replace(/Defined in: .*?((?:packages)\/.*)$/, 'Defined in: `$1`'),
    )
    .trim()

  writeFileSync(file, `---\ntitle: ${JSON.stringify(title)}\n---\n\n${body}\n`)
}

// Sidebar ordering: the API landing page, then one section per package.
writeMeta(stageRoot, 'API Reference', ['index', ...packages])
for (const name of packages) {
  const directory = resolve(stageRoot, name)
  const present = sections.filter((section) =>
    readdirSync(directory, { withFileTypes: true }).some(
      (entry) => entry.isDirectory() && entry.name === section,
    ),
  )
  writeMeta(directory, packageMeta[name].title, ['index', ...present])
}

writeFileSync(
  resolve(stageRoot, 'index.mdx'),
  `---
title: API Reference
description: Generated reference for every export across the four packages.
---

Generated from the TSDoc comments in each package's source by \`typedoc\`. Every
symbol links back to the file and line that defines it.

For task-oriented documentation, start with [Packages](/docs/packages); this
section is the exhaustive surface.

${packages
  .map((name) => `- [\`${scope}/${name}\`](/docs/api/${name}) — ${packageMeta[name].description}`)
  .join('\n')}
`,
)

// Atomic-enough swap: remove then rename, so the window where the tree is
// missing is a single syscall rather than the whole generation run.
rmSync(apiRoot, { force: true, recursive: true })
renameSync(stageRoot, apiRoot)

console.log(`API reference generated for ${packages.length} packages`)
