export { deriveTextDecorations } from './decorations.js'
export {
  InvalidLayoutInputError,
  TextPreparationError,
  type TextPreparationErrorCode,
} from './errors.js'
export {
  canonicalFixtureJson,
  deriveSelectionRects,
  validateLayoutFixtureDocument,
} from './fixture.js'
export { layoutResolvedText } from './layout.js'
export { prepareText } from './preparation.js'
export { getSelectionRects } from './selection.js'
export { layoutPreparedText, layoutText } from './text.js'
export type {
  CaretStop,
  DecorationBounds,
  DecorationClip,
  DecorationColor,
  DecorationDerivationOptions,
  DecorationKind,
  DecorationSegment,
  DecorationSkipInk,
  DecorationSpan,
  DecorationStyle,
  FixtureClassification,
  FixtureEvidence,
  FixtureEvidenceLayer,
  FontRegistry,
  HorizontalAnchor,
  LayoutAlignment,
  LayoutBounds,
  LayoutDecorationMetricRange,
  LayoutFixtureDocument,
  LayoutLine,
  LayoutOverflowWrap,
  LayoutPolicy,
  LayoutPolicyFixture,
  LayoutResult,
  LayoutSelectionExpectation,
  LayoutWhiteSpace,
  LineBreakKind,
  LineBreakOpportunity,
  ParagraphDirection,
  PositionedGlyph,
  PreparedSegment,
  PreparedText,
  PrepareTextInput,
  ResolvedGlyph,
  ResolvedLayoutInput,
  ResolvedRunMetrics,
  ResolvedShapedRun,
  SelectionQuery,
  SelectionRect,
  TextDecorationResult,
  TextStyle,
  TextStyleRange,
  Utf16Range,
  VerticalAnchor,
} from './types.js'
